//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FiftyOne.IpIntelligence.Engine.OnPremise.Interop {

public enum IpTypeSwig {
  FIFTYONE_DEGREES_EVIDENCE_IP_TYPE_IPV4 = 0,
  FIFTYONE_DEGREES_EVIDENCE_IP_TYPE_IPV6 = 1,
  FIFTYONE_DEGREES_EVIDENCE_IP_TYPE_INVALID = 2
}

}
